import type { Messages } from '$lib/translate';

export type CategorySuggestionMessage = `categories.list.${string}` & Messages;

export const categoryDataList: Record<CategorySuggestionMessage, string> = {
  'categories.list.Alcohol': 'mdi:alcohol',
  'categories.list.Bank': 'mdi:bank',
  'categories.list.Beauty': 'mdi:face-woman-shimmer',
  'categories.list.Books': 'mdi:bookshelf',
  'categories.list.Car': 'mdi:car',
  'categories.list.Children': 'mdi:baby',
  'categories.list.Clothes': 'mdi:tshirt-crew',
  'categories.list.Connection': 'mdi:access-point',
  'categories.list.Debts': 'mdi:cash-return',
  'categories.list.Delivery': 'mdi:truck-delivery-outline',
  'categories.list.Donations': 'mdi:donation',
  'categories.list.Education': 'mdi:education-outline',
  'categories.list.Electronics': 'mdi:devices',
  'categories.list.Entertainment': 'mdi:gamepad-variant',
  'categories.list.Fitness': 'mdi:gymnastics',
  'categories.list.Fuel': 'mdi:fuel-pump',
  'categories.list.Furniture': 'mdi:table-chair',
  'categories.list.Gifts': 'mdi:gift',
  'categories.list.Hobby': 'mdi:art',
  'categories.list.Insurance': 'mdi:shield-half-full',
  'categories.list.Investment': 'mdi:chart-finance',
  'categories.list.Journeys': 'mdi:hiking',
  'categories.list.Laundry': 'mdi:laundrette',
  'categories.list.Loans': 'mdi:bank',
  'categories.list.Lunches': 'mdi:restaurant',
  'categories.list.Medicine': 'mdi:hospital-box',
  'categories.list.Movies': 'mdi:local-movies',
  'categories.list.Music': 'mdi:music',
  'categories.list.Parking': 'mdi:parking',
  'categories.list.Pets': 'mdi:pets',
  'categories.list.Photos': 'mdi:camera',
  'categories.list.Products': 'mdi:shopping-outline',
  'categories.list.Purchases': 'mdi:shop',
  'categories.list.Renovation': 'mdi:hammer-wrench',
  'categories.list.Restaurants': 'mdi:restaurant',
  'categories.list.Services': 'mdi:power-plug',
  'categories.list.Stationery': 'mdi:pencil-ruler',
  'categories.list.Subscriptions': 'mdi:repeat-variant',
  'categories.list.Sweets': 'mdi:cupcake',
  'categories.list.Technic': 'mdi:washing-machine',
  'categories.list.Textile': 'mdi:cloth',
  'categories.list.Tobacco': 'mdi:smoking',
  'categories.list.Transport': 'mdi:transportation',
};
