export const categoryIcons = {
  food: [
    // food
    'mdi:food',
    'mdi:restaurant',
    'mdi:food-turkey',
    'mdi:food-variant',
    'mdi:food-apple',
  ],
  shopping: [
    // shopping
    'mdi:shop',
    'mdi:cart',
    'mdi:shopping',
    'mdi:tshirt-crew',
    'mdi:shoe-sneaker',
  ],
  transport: [
    // transport
    'mdi:transportation',
    'mdi:car',
    'mdi:taxi',
    'mdi:bus',
    'mdi:truck',
    'mdi:train',
    'mdi:car-side',
    'mdi:bus-side',
    'mdi:sail-boat',
    'mdi:airplane',
    'mdi:fuel-pump',
    'mdi:parking',
    'mdi:road-variant',
    'mdi:scooter-outline',
    'mdi:bicycle',
  ],
  hobby: [
    // hobby
    'mdi:ski',
    'mdi:snowboard',
    'mdi:gym',
    'mdi:soccer',
    'mdi:basketball',
    'mdi:table-tennis',
    'mdi:sprout',
    'mdi:flower',
    'mdi:camera',
    'mdi:music',
    'mdi:music-clef-treble',
    'mdi:guitar-acoustic',
    'mdi:gamepad-variant',
    'mdi:television-classic',
    'mdi:pets',
    'mdi:cat',
    'mdi:dog',
    'mdi:horse',
    'mdi:globe',
    'mdi:routes',
    'mdi:hiking',
  ],
  medicine: [
    // medicine
    'mdi:medical-bag',
    'mdi:hospital-box',
    'mdi:tooth',
    'mdi:syringe',
    'mdi:drugs',
    'mdi:baby-bottle',
    'mdi:baby-carriage',
    'mdi:baby',
    'mdi:child-toy',
    'mdi:hair-dryer',
    'mdi:face-woman-shimmer',
  ],
  home: [
    // home
    'mdi:home',
    'mdi:phone-classic',
    'mdi:power-plug',
    'mdi:electricity',
    'mdi:water',
    'mdi:garbage',
    'mdi:heater',
    'mdi:cable-data',
    'mdi:cctv',
    'mdi:internet',
    'mdi:hammer-wrench',
  ],
  other: [
    // other
    'mdi:briefcase-outline',
    'mdi:briefcase',
    'mdi:credit-card',
    'mdi:credit-card-outline',
    'mdi:folder-outline',
    'mdi:folder-pound-outline',
    'mdi:office-building',
    'mdi:bank',
    'mdi:cash-multiple',
    'mdi:trending-up',
    'mdi:trending-down',
    'ic:baseline-percent',
  ],
};
