import { addMessages } from 'svelte-i18n';
import type { Dictionary } from './messages';

export const enDict: Dictionary = {
  // Common
  'common.back': 'Back',
  'common.select': 'Select',
  'common.available_variants': 'Available variants',
  'common.optional': 'optional',
  'common.loading': 'Loading...',
  'common.show_more': 'Show more',
  'common.sorting': 'Sorting',
  'common.sort_by': 'Sort by',
  'common.sort_direction': 'Sort direction',
  'common.ascending': 'Ascending',
  'common.descending': 'Descending',
  'common.grouping': 'Grouping',
  'common.no_items': 'No items yet',
  'common.create': 'Create',
  'common.save': 'Save',
  'common.add': 'Add',
  'common.save_changes_failure': 'Failed to save changes',
  'common.save_changes_success': 'Changes were saved',
  'common.search': 'Search',
  'common.clear': 'Clear',
  'common.cancel': 'Cancel',
  // Auth
  'auth.login.title': 'Login',
  'auth.login': 'Login',
  'auth.password': 'Password',
  'auth.sign_in': 'Sign in',
  'auth.incorrect_login_or_password': 'Incorrect login or password',
  'auth.failed_to_login': 'Failed to login',
  'auth.register.title': 'Register',
  'auth.name': 'Name',
  'auth.phone': 'Phone',
  'auth.repeat_password': 'Repeat password',
  'auth.passwords_must_be_same': 'Passwords must be same',
  'auth.register': 'Sign up',
  'auth.user_already_exists': 'User already exists',
  'auth.failed_to_register': 'Failed to register',
  'auth.logout.title': 'Logout',
  'auth.sign_out': 'Sign out',
  'auth.profile': 'Profile',
  'auth.logged_in_as': 'You are logged in as {name}!',
  'auth.not_logged_in': 'You are not logged in',
  // Accounts
  'accounts.title': 'Accounts',
  'accounts.create_account': 'Create account',
  'accounts.create_account_failure': 'Failed to create account',
  'accounts.create_account_success': 'Account was created',
  'accounts.edit_account': 'Update account',
  'accounts.delete_account': 'Delete account',
  'accounts.delete_account_confirm': 'Are you sure want to delete account?',
  'accounts.delete_account_confirm_description':
    "All account's operations also will be deleted. This action can't be undone.",
  'accounts.delete_account_failure': 'Failed to delete account',
  'accounts.delete_account_success': 'Account was deleted',
  'accounts.name': 'Name',
  'accounts.currency': 'Currency',
  'accounts.icon': 'Icon',
  'accounts.color': 'Color',
  // Categories
  'categories.title': 'Categories',
  'categories.incomings': 'Incomings',
  'categories.outgoings': 'Outgoings',
  'categories.create_category': 'Create category',
  'categories.create_category_success': 'Category was created',
  'categories.create_category_failure': 'Failed to create category',
  'categories.edit_category': 'Edit category',
  'categories.delete_category': 'Delete category',
  'categories.delete_category_failure': 'Failed to delete category',
  'categories.delete_category_success': 'Category was deleted',
  'categories.name': 'Name',
  'categories.icon': 'Icon',
  // Groups
  'groups.title': 'Groups',
  'groups.create_group': 'Create group',
  'groups.name': 'Name',
  'groups.edit_group': 'Edit group',
  'groups.edit_group_name': "Edit group's name",
  'groups.users': 'Users',
  'groups.add_user': 'Add user',
  'groups.failed_to_add_user': 'Failed to add user',
  'groups.username': 'Username',
  'groups.delete_group': 'Delete group',
  // Transactions
  'transactions.title': 'Operations',
  'transactions.create_transaction': 'Create operation',
  'transactions.new_transaction': 'New operation',
  'transactions.account': 'Account',
  'transactions.account_is_required': 'Select an account firstly',
  'transactions.date': 'Date',
  'transactions.amount': 'Amount',
  'transactions.category': 'Category',
  'transactions.category_is_required': 'Select a category firstly',
  'transactions.comment': 'Comment',
  'transactions.edit_transaction': 'Edit operation',
  'transactions.delete_transaction': 'Delete operation',
  // Settings
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.select_language': 'Select language',
  'settings.common': 'Common',
  'settings.darkMode': 'Dark mode',
};

addMessages('en-US', enDict);
