/// <reference lib="webworker" />

import { build, files, prerendered, version } from '$service-worker';

const worker = self as unknown as ServiceWorkerGlobalScope;
const FILES = `cache-${version}`;
const OFFLINE = `offline-${version}`;
// This is a build-time public shell, never a cached authenticated document.
const APP_ENTRY = '/';

// `build` is an array of all the files generated by the bundler,
// `files` is an array of everything in the `static` directory
const to_cache = build.concat(files, prerendered);
const staticAssets = new Set(to_cache);

worker.addEventListener('install', (event) => {
  // Let open tabs finish with their matching HTML/assets before activating an update.
  event.waitUntil(caches.open(FILES).then((cache) => cache.addAll(to_cache)));
});

worker.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then(async (keys) => {
      // delete old caches
      for (const key of keys) {
        if (/^(cache|offline)-/.test(key) && key !== FILES && key !== OFFLINE) {
          await caches.delete(key);
        }
      }

      await worker.clients.claim();
    }),
  );
});

/** CacheStorage can be unavailable under storage pressure or browser privacy settings. */
async function matchCached(cacheName: string, request: Request | string) {
  try {
    const cache = await caches.open(cacheName);
    return await cache.match(request);
  } catch {
    return undefined;
  }
}

/** Network-first for existing deep links; never delay delivery on a cache write. */
async function fetchAndCache(event: FetchEvent) {
  const request = event.request;

  try {
    const response = await fetch(request);
    const noStore = response.headers.get('cache-control')?.toLowerCase().includes('no-store');
    if ((response.ok && !response.redirected) || noStore) {
      const copy = response.clone();
      event.waitUntil(
        caches
          .open(OFFLINE)
          .then((cache) => (noStore ? cache.delete(request) : cache.put(request, copy)))
          .catch(() => {
            // Storage pressure must not turn a successful request into a network error.
          }),
      );
    }
    return response;
  } catch (err) {
    const response = await matchCached(OFFLINE, request);
    if (response) return response;
    throw err;
  }
}

worker.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || event.request.headers.has('range')) return;

  const url = new URL(event.request.url);

  if (url.origin === 'https://api.iconify.design') {
    event.respondWith(fetchAndCache(event));
    return;
  }

  // Financial/API responses must always go to the network, never a shared URL cache.
  if (url.origin !== worker.location.origin || url.pathname.startsWith('/api/')) return;

  if (event.request.mode === 'navigate' && url.pathname === APP_ENTRY) {
    event.respondWith(matchCached(FILES, APP_ENTRY).then((shell) => shell || fetch(event.request)));
    return;
  }

  // don't try to handle e.g. data: URIs
  const isHttp = url.protocol.startsWith('http');
  const isDevServerRequest = url.hostname === self.location.hostname && url.port !== self.location.port;
  const isStaticAsset = url.host === self.location.host && staticAssets.has(url.pathname);
  const skipBecauseUncached = event.request.cache === 'only-if-cached' && !isStaticAsset;

  if (isHttp && !isDevServerRequest && !skipBecauseUncached) {
    event.respondWith(
      (async () => {
        // always serve static files and bundler-generated assets from cache.
        // if your application has other URLs with data that will never change,
        // set this variable to true for them and they will only be fetched once.
        const cachedAsset = isStaticAsset && (await matchCached(FILES, url.pathname));

        return cachedAsset || fetchAndCache(event);
      })(),
    );
  }
});
